### ISSUE TITLE
[Feature Requests] Collapsible items and copy/paste

### ISSUE THREAD

**Issue by reality-exe** [VRCFury/VRCFury#10]
Being able to collapse items like `Force Object State` or `Toggle` would be really nice to make it a little easier to work with.

Same goes for copying (Mainly for Toggle) as if you're making multiple toggleable objects that are similar it could speed the process up a little more.

**Comment by SenkyDragon** [comment]
Soon(ish), all vrcfury features are going to be split out into their own components. This will make copy+paste easier, since you can copy any of the components using unity's built in copy+paste. Collapsing is also a thing, but unity is pretty janky about collapsing components -- if you collapse one, leave, then come back, they will all be collapsed for no reason.

It's worth noting that for organizational purposes, you can put most vrcfury features on any object you want. You could put your force object states and toggles on child empties named after what they do.

**Comment by SenkyDragon** [comment]
I'm going to close this as it will be covered by #20
