### ISSUE TITLE
Allow a destructive workflow by applying individual features

### ISSUE THREAD

**Issue by TayouVR** [VRCFury/VRCFury#109]
There are a lot of (VRChat) creators, who would like to use features like SPS, but don't like that VRCFury copies the entire avatar and works on things "behind the users back". It is very opaque to anyone, who isn't super well versed in unity and reads the source code.

There should be a button on each feature to apply just it, to the current avatar, not to a copy.
This will be very difficult to implement and completely goes against the non destructive nature of VRCFury, but some people don't want to use a tool that doesn't really say what it does, without a way to look on your own.

**Comment by TayouVR** [comment]
A Technical documentation would also come a long way. Explaining how each feature works and what it actually does. Not every user can read C# code, so actually writing somewhere e.g. by what logic blendshape optimizer figures out which ones are used, how WD fix does its things, and how all the other features work.

I would be willing to PR some of that work myself if you @SenkyDragon accept any contributions to a official, technical documentation on vrcfury.com

**Comment by SenkyDragon** [comment]
Making SPS work in a destructive manner is essentially never going to happen. There are so many moving parts in play that "undoing" the changes would be impossible, and breakage would be extremely easy. For instance, all animations that contribute to the final scale of a plug have additional bindings added which contribute to a blendtree, allowing us to calculate the final scale of the plug to pass to the shader. If the user "baked this in", then made any changes to the plug scale, or to any of the animations affective the plug scale, or the size of any parent objects, or any of the logic within the blendtrees, then the calculated scale of the plug would be incorrect. Not only that, but "fixing" this broken scenario would be basically impossible because undoing all the changes that VRCFury makes would be a nightmare.

Documentation contributions are always very much appreciated at https://github.com/VRCFury/VRCFury.com
