### ISSUE TITLE
[Feature Request] "Do nothing" option for Force Object State

### ISSUE THREAD

**Issue by PinballsWizard** [VRCFury/VRCFury#12]
Use case: Avatar base that comes with multiple options separated out into gameobjects that have their physbones and meshes under them in a hierarchy to allow for easier optimization.  Currently to get this optimization prefabs would need to be unpacked and items deleted, which is simple enough but destructive.

Adding a "Do nothing" option would allow avatar authors to add the Force Object State that would not disrupt avatar upload or remove features, but can instruct users to simply change a drop down to "Delete" to remove entire parts of the avatar for optimization at upload

Example avatar that could be improved using this: https://razra.gumroad.com/l/razkobold

**Comment by SenkyDragon** [comment]
Fair enough, however, I was sort of planning on replacing Force Object State with two separate components: `Delete Objects During Upload` and `Apply Animations During Upload` (which would allow not only "turn on" and "turn off" actions, but also "set blendshape value", "apply animation clip", and everything else that the vrcfury animation editor supports).

Not really sure how it would fit into that ecosystem. I guess since we're moving to one-component-per-feature, you could just make a bunch of separate `Delete Objects During Upload` components, then turn them all off and instruct users to turn them back on.

**Comment by PinballsWizard** [comment]
With the restructuring that makes sense, just glad that the functionality will be possible this way, thank you!

**Comment by SenkyDragon** [comment]
I'm going to close this as replaced by #21
