### ISSUE TITLE
Scene marked dirty after uploads

### ISSUE THREAD

**Issue by babo4d** [VRCFury/VRCFury#170]
Thought this might be an SDK bug related to the old avatar descriptor issue. But I found that it only happens when uploading with VRCFury components added. I am able to reliably reproduce this issue with the basic SDK tutorial robot with a blank VRCF component added, and reliably *not* reproduce when it is removed.

**Comment by SenkyDragon** [comment]
I think this is going to be a wontfix. It's quite literally a miracle that the scene doesn't get marked as dirty when the VRCSDK is working alone, since it creates the upload clone _in the same scene_, packages it, and then deletes the clone, all of which definitely constitutes a dirtying change. However, because unity, object creation and deletion don't count as "dirtying" actions for some reason.

VRCFury makes a lot of changes that are not just creation and deletion that we need to ensure that unity picks up and reserializes. This includes simply changing the controllers on the avatar descriptor within the clone. The only real alternative is for us to just save the scene automatically after building, but that also seems dumb.
