### ISSUE TITLE
[Bug] TrackingConflictResolverBuilder breaks on my specific layer

### ISSUE THREAD

**Issue by TayouVR** [VRCFury/VRCFury#187]
I have extracted the following layer from my avatar as it was causing the tracking control logic in VRCFury to build something, which in game forced my avatar into animation pose upon loading in.
[TMP_Tracking_Control_Testing.zip (.controller file with a single layer)](https://github.com/VRCFury/VRCFury/files/13540294/TMP_Tracking_Control_Testing.zip)
This is a leftover layer from my avatars scaling prefab, which I forgot to remove.
Due to VRCFurys habit of barely printing any logs I wasn't able to pin down where the problem came from. My unity and VRC knowledge lead me to believe it was the TrackingConflictResolverBuilder within VRCFury causing the problem and blocking it from executing by returning right at the start in Apply() did fix the issue. But that is obviously a workaround around a bug.

In these kind of situations i would like to be able to disable automatic features btw, see https://github.com/VRCFury/VRCFury/issues/186

**Comment by SenkyDragon** [comment]
Not a bug. In your attached controller, the default value of the AvatarSize/IsResizing parameter is 1, which means (without any control from a vrchat menu or anything), it immediately goes into the `freeze tracking` state, which marks all the bones as animated, and then it never leaves it.

There is a vrchat bug that causes tracking control commands to be ignored for a few frames upon load, but vrcfury fixes this issue. The reason it worked for you previously is because your broken layer was incorrectly not being applied due to the vrchat bug.

**Comment by TayouVR** [comment]
weird, that that was never a problem on its own then...
Before the tracking control stuff got added to VRCFury the animator didn't trigger the tracking control.

🤷
