### ISSUE TITLE
Reordering items in Gestures causes Unity to crash

### ISSUE THREAD

**Issue by Vlad-M-1** [VRCFury/VRCFury#206]
Reordering items in Gestures causes Unity to crash.
Tested in two different projects.

VRCFury 1.672.0
Unity 2022.3.6f1

**Comment by ProffDea** [comment]
In Unity 2022.6f1 with VRCFury 1.677.0, re-ordering any items in a VRCFury Gesture Component with at least two items with any actions (object toggle, animation clip, blendshape) will freeze unity with a progress bar window popping up. If there are only a few items, it can finish loading. However, if there are a lot of items such as 14, the loading will go on long enough until Unity crashes.

At least two items need to have actions added in order to replicate the bug. Re-ordering items functions properly when there is only one action or none.

**Comment by NikkyAI** [comment]
still happens in VRCFury 1.6.92.0 for me

**Comment by imagitama** [comment]
I also reported this in !229 and author Senky replied that it is a Unity bug not VRCFury related

**Comment by SenkyDragon** [comment]
This was fixed by unity in 2022.3.22
