### ISSUE TITLE
Avatar goes through floor with VRCFury and Avatar Optimizer

### ISSUE THREAD

**Issue by creamcast** [VRCFury/VRCFury#225]
When I try to upload avatar with anatawa12's  Avatar Optimizer and VRCFury to use Gogoloco the avatar will be half way through the floor when it stands idle. I can use one or the other but as soon as I try to use both at the same time it will break. What could be causing the avatar to go through the floor (when I walk it seems to be at the correct height)? AvatarOptimizer is a collection of optimization tools https://github.com/anatawa12/AvatarOptimizer. It modifies avatar at compile time so maybe something is not linking correctly..?

**Comment by SenkyDragon** [comment]
This issue board is primarily for verified vrcfury bugs or feature requests. For support, please join the discord at https://vrcfury.com/discord . However, beware that we do not generally provide support for issues caused by other plugins. If the build works without the optimizer, then I would suggest asking for support from the optimizer team.

**Comment by anatawa12** [comment]
This might be because of #216. for build time, as I described in #216, VRCFury breaks Avatar Optimizer. (Avatar Optimizer is a tool executed on Optimizing Phase of NDMF.)
For play mode, it's almost impossible to support execution order so will not work well for now. 
(In upcoming NDMF, v1.3.0, NDMF will have workaround for #216 so PlayMode preview will work well except AAO will not be executed unless you use Av3Emulator.)

Today, I wrote information about VRCFury compatibility. Please refer this announcement for future updates of compatibility between VRCFury and Avatar Optimizer. 
https://github.com/anatawa12/AvatarOptimizer/discussions/860
