### ISSUE TITLE
Constrained Proportions feature is too expensive to be enabled by default

### ISSUE THREAD

**Issue by GotoFinal** [VRCFury/VRCFury#264]
Spend long time trying to understand why my unity felt very slow after installing vrcfury, and finally found that its caused by the automatic switching of Constrained Proportions.
The actually laggy part is `PrefabUtility.RevertPropertyOverride` as it internally causes ALL `[ExecuteInEditMode]` `OnAwake` and `OnEnable` methods of the root prefab to be executed, so with very complex avatar with some tools any clicking in hierarchy or editor causes lag spikes of hundredths of milliseconds as its like disabling and enabling of whole avatar on every click.

And typical user will just not even know where it might be coming from and just wonder why his unity is running slower. At the same time just reverting should not be removed as then the tool is no longer non destructive. 

Personally I don't even understand why this feature exists, it does nothing useful and can cause issues like that. If someone plans to scale something only on one axis, he will do it anyways, not even knowing that the toggle was changed by the tool, as tool does nothing to inform the user that this might cause issues. Will try to scale, notice all values changing, switch the toggle, and scale again.

Related to this change: 
https://github.com/VRCFury/VRCFury/commit/e838c2cf29cc4764ed8709c8cbf9161168c42791

**Comment by SenkyDragon** [comment]
`The actually laggy part is PrefabUtility.RevertPropertyOverride as it internally causes ALL [ExecuteInEditMode] OnAwake and OnEnable methods of the root prefab to be executed`

Well, that's annoying 😓

**Comment by SenkyDragon** [comment]
> Personally I don't even understand why this feature exists

Suffice to say, you are likely not the typical user. Prior to introduction of this feature, it was exceedingly common for VRCF users to footgun by accidentally non-uniformly scaling things like SPS components, where it's extremely important for collider sizes to be predictable and consistent. This usually happened because they weren't aware they could scale the central cube in the GUI, and instead would just drag each axis, making it "look right" while simultaneously introducing Skew to their bones and making contacts unpredictable.

"Why does the length of my arm change when I bend it?"

**Comment by SenkyDragon** [comment]
There haven't been any other complaints on this topic since this issue was filed, so this will probably remain as it is, and can be disabled in the settings or reinvestigated if it becomes a bigger issue in the future.

**Comment by lackofbindings** [comment]
Oh wow I can't believe this was VRCFury's fault this whole time. I though it was just yet another bug in Unity 2022. I'm glad there's an option to turn this off. Can't say I notice any performance hit but wow, its the absolute most annoying thing to have it generate new overrides on every single transform you touch.

**Comment by SenkyDragon** [comment]
Beware that creating transforms with non-uniform scales is not something most users should be doing on a regular basis. Using a non-uniform scale causes sheer, which means that all children of that bone will change shape depending on which direction they are rotated. This means (for example) if you apply a non-uniform transform to make your arm longer, your hand will shrink when you point it in, and grow when you point it out.

Non-uniform transforms also do not apply to colliders and contacts, which means that those capsules you see in the contact editor will randomly be inaccurate depending on which direction the bone is facing.

As an alternative, you can often "stretch" rigged bones by simply moving the children further away rather than messing with the scale.

We enable constrained proportions by default because the average vrchat user doesn't understand these limitations, and winds up shooting themselves in the foot because unity makes it so easy to accidentally scale one axis separately from the others, even when you're not trying to do it on purpose.
