### ISSUE TITLE
[Feature Request] Toggle slider Value from to

### ISSUE THREAD

**Issue by Armageddit** [VRCFury/VRCFury#284]
i Have a Problem with material property

the brightness goes from -1 to 1
but the from value is only use the is state in poiomi shader and Value is what ther slider at 1 is

the material Slot Number is also missing

![Screenshot 2024-05-09 154757](https://github.com/VRCFury/VRCFury/assets/49964721/63847caa-2007-49a0-b951-a620dc5239e1)
![image](https://github.com/VRCFury/VRCFury/assets/49964721/dc49d242-9c4e-4cdc-8012-30a45034f86a)

**Comment by Armageddit** [comment]
[#use-slider-wheel](https://vrcfury.com/components/toggle#use-slider-wheel)
0% will be the avatar default state...
-1 The default brightness looks black and it's a problem to work with Unity

**Comment by SenkyDragon** [comment]
Unity does not allow controlling a material properties for a specific slot within a renderer -- it always applies to all slots, which is why the slot is not an available field. If you want to override the "from" value, use an Apply During Upload component. For support, please use the vrcfury discord, this issue board is for verified bugs and approved feature requests only.
