### ISSUE TITLE
[1.161.0] FixWriteDefaults set to Disabled still modifies Write Defaults value

### ISSUE THREAD

**Issue by CyanLaser** [VRCFury/VRCFury#39]
Using the FixWriteDefaults feature with Fix Mode set to Disabled will still modify the Write Defaults value on animator states.

# Expectation
In Animator Controllers with mixed Write Default usage and the FixWriteDefaults feature set to Fix Mode Disabled should not change any Write Defaults values.

# Actual
VRCFurry will decide the Write Defaults value to be used for all states, potentially breaking some setups.

# Repro
1. Create an animator controller with two states. These can be empty
1. Have the default state with Write Defaults off
1. Have the other state with Write Defaults on
1. Add to avatar using VRCFury with FullController feature
1. Add the FixWriteDefaults Feature with Fix Mode set to Disabled
1. Press Play to build VRCFury
1. Observe resulting controller has both states with the same Write Default Value of off

Having the default state with Write Defaults on and the other state with Write Defaults off does not change the value of write defaults in the generated controller, showing different behavior depending on the order of the states.

# Notes
[Guides on using Direct Blend Trees](https://notes.sleightly.dev/dbt-combining/) suggest it is required that the state has Write Defaults set to true. The [OSCmoooth editor tool](https://github.com/regzo2/OSCmooth) generates blend trees with Write Defaults set to false. Using VRCFury's to combine animators with both of these types of states will update the Write Defaults value, breaking one of the systems. Having the FixWriteDefaults feature with Fix Mode Disabled will remove the warning that the animators could have issues, but there is no way to prevent changes to Write Default states.

**Comment by SenkyDragon** [comment]
This is by design. Fix Write Defaults only affects the avatar's pre-existing states. All states which are added by vrcfury, including those from Full Controllers, are managed and adjusted to match the WD of the rest of the avatar. Direct Blend Trees are already special cased by VRCF to ALWAYS be WD on, regardless of their source. If this is not happening in your avatar, be sure your VRCF is up to date.

If you continue to experience issues beyond this explanation, feel free to re-open.
