### ISSUE TITLE
[Feature Request] Add option to only apply Blendshape Optimizer etc

### ISSUE THREAD

**Issue by MrDj200** [VRCFury/VRCFury#41]
Hi,
I stumbled over an avatar where adding any VRCF component breaks _a lot_ of the avatars functionality.
Would it be possible to have an option to apply optimizations (Blendshapes, Anchor override, etc) that don't touch animators, without having VRCF rebuild the avatars animators?

I'm assuming it's something to do with Write Defaults. I tried all 4 different VRCF options (ON, OFF, Auto, Disable) and all caused issues with the avatars animator. 

VRCF Version: 1.165.0

**Comment by SenkyDragon** [comment]
What was the breakage? Unfortunately vrcf makes a lot of assumptions about the state of the avatar which makes cleanly separating features like this pretty impossible. Were animations "sticking"?

**Comment by MrDj200** [comment]
Mostly blendshapes that were driven by something were going crazy. They cycled up and down infinitely. 
Not all of them did this, but a lot of them iirc

**Comment by SenkyDragon** [comment]
Unfortunately we cannot add a function to permanently apply a feature, as described in #45. The issue you describe sounds like a write defaults conflict, which is usually a pre-existing issue on the avatar which may be exacerbated by tweaks that VRCF makes in order to function (primarily, removing the global mask from the FX controller). I try my best to ensure that VRCF works on all avatars regardless of design, but sometimes some slip by. If you're able to provide more information about the cause of the issue, or can possibly DM me a copy of the project, it's more likely that we can fix the underlying issue that is causing your breakage in the first place.
