### ISSUE TITLE
Unity Crash when Blendshape Optimizer is present while Lyuma's emulator is enabled

### ISSUE THREAD

**Issue by AtriusX** [VRCFury/VRCFury#78]
I've noticed a crashing issue developing recently with Unity that seems to only occur when a VRCFury component with the blend shape optimizer is present and av3 emulator is enabled. The crash occurs when entering play mode, and references what appears to be a null pointer exception of some form. I'm not sure what exactly caused this issue to occur as this effects all versions of VRCFury that I've tested, including older versions. This only began occurring within the last few days, so I have a minor suspicion that it might be SDK-related.

I had a friend check this out on their project as well since I wasn't sure if this was corruption or not, but it appears they were able to reproduce the problem in their project as well. The errors from my project and theirs are included below.

<img width="397" alt="1" src="https://github.com/VRCFury/VRCFury/assets/7331441/3a82c0b9-a639-44a8-a335-4926c091c8c3"> <img width="397" alt="2" src="https://github.com/VRCFury/VRCFury/assets/7331441/9ae2414f-4f79-4448-b932-93d7ee6e53e6">

**Comment by SenkyDragon** [comment]
This is because the most recent release of av3emulator began running vrchat preupload hooks by default. The point when they trigger vrcfury to run is unsafe to make these changes, causing the crash. I believe you can prevent av3emulator from running preupload hooks in its options, but if you don't need the additional features, I'd really just recommend using gesture manager which is much more lightweight.
