### ISSUE TITLE
Intelligently merge physbones in armature link

### ISSUE THREAD

**Issue by SenkyDragon** [VRCFury/VRCFury#85]
Sometimes clothing artists do... weird things and place a physbone on bones within the clothing armature that already exist on the avatar, for instance, a physbone on the Chest to handle things that the clothing artist has added to the chest bone. This is bad practice, but it's something we still need to deal with.

We can work around this issue by retaining the physbone, and excluding every merged child object from it, leaving only the added children that the prop is providing. If there are 0 remaining children, we should just remove the physbone entirely.

**Comment by babo4d** [comment]
I am making a prefab where I have an alternative phys bone setup for existing bones where instead of replacing the existing phys bones I use the Root Transform to target them in my prefab, so that I can toggle between the existing setup and the new setup. Since there is no way to handle this automatically I would have to instruct users to find the existing bones and drag them all to the correct slot on the phys bone components on their own.

It seems that what I need is an option like Skin Rewrite but without the skin, just merging bone hierarchies. I did try that option but it did not seem to work so I assume it requires a mesh.
